### ISSUE TITLE
Trying to build binary for Pimoroni Pico VGA Demo Base

### ISSUE THREAD

**Issue by mwedmark** [diyelectromusic/picodexed#2]
I've managed to build binary in Windows (after many changes done to many things) for this board
[Board](https://shop.pimoroni.com/products/pimoroni-pico-vga-demo-base?variant=32369520672851)

I didn't manage to autochange files using diff files (should have been a multi file patch maybe??) so I did the changes manually. I hope I got it right..

I can see that the board receives USB-MIDI (LED blinking) via USB-cable from Windows DAW called LMMS. 
But no sound on I2S?? Should the current code work with that I2S?

I've changed the pin output to suit the new board?? I think...
-snip-
//#define I2S_DATA_PIN    9
//#define I2S_BCLK_PIN    10
//#define I2S_LRCLK_PIN   11  // Implied by BCLK=10
#define I2S_DATA_PIN    31
#define I2S_BCLK_PIN    32
#define I2S_LRCLK_PIN   34  // Implied by BCLK=10
-snip-

Any ideas? Maybe some knowledgeable could present working binaries for this sister board too?

**Comment by diyelectromusic** [comment]
The fact that the 5100, 5101, 5102 all share the same datasheet and pinout seems to imply they should be drop-in compatible, but I've only got 5102 modules to try here I'm afraid.

I seem to recall that the reason the LRCLK_PIN was implied from BCLK is because the Pico's PIO implementation of I2S needed them on consecutive GPIO pins so I don't quite know what's going on there...

Actually, looking at the pinout diagram, they've labelled physical pins, but not GPIO numbers!?  So I think you'd need to use:
#define I2S_DATA_PIN 26  // GPIO 26 on pin 31
#define I2S_BCLK_PIN 27  // GPIO 27 on pin 32
#define I2S_LRCLK_PIN 28 // Implied by BCLK=27; GPIO 28 on pin 34

But I haven't looked at this code for a while now, so anything could be happening really :)

Kevin

**Comment by mwedmark** [comment]
Good grief, thank you! That was the missing link after changing a lot of other things to get it to compile!
Super, thanks! next step is to play some MIDI-files AND connect it to my MIDI-synth and play some!
Does the code include working reverb effect or was it removed? How is it added to sound?
